#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
        /config/{adguard,log/adguard} \

# install latest version adguard home
wget https://github.com/AdguardTeam/AdGuardHome/releases/download/${ADGUARD_VERSION}/AdGuardHome_linux_armv6.tar.gz -P /tmp

tar -xvf /tmp/AdGuardHome_linux_armv6.tar.gz -C /tmp

gpg --verify /tmp/AdGuardHome/AdGuardHome.sig

cp /tmp/AdGuardHome/AdGuardHome /usr/sbin/adguard

rm -rf /tmp/AdGuardHome*

# permissions
chown -R alpine:alpine \
        /config \
        /run

chmod -R g+w \
        /config/{adguard,log}

chmod -R 644 /etc/logrotate.d /config/log
