#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/{adguard,log/adguard} \


wget https://github.com/AdguardTeam/AdGuardHome/releases/download/${ADGUARD_VERSION}/AdGuardHome_${ADGUARD_VERSION}_linux_arm.tar.gz -P /tmp &&
tar -xvf /tmp/AdGuardHome_${ADGUARD_VERSION}_linux_arm.tar.gz &&
cp ./AdGuardHome/AdGuardHome /usr/sbin/adguard && rm -rf /AdGuardHome && rm -rf /tmp/AdGuardHome

# permissions
chown -R alpine:alpine \
	/config \
	/run 

chmod -R g+w \
	/config/{adguard,log}

chmod -R 644 /etc/logrotate.d /config/log