#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/{adguard,log/adguard} \


wget https://static.adguard.com/adguardhome/release/AdGuardHome_linux_armv6.tar.gz -P /tmp &&
tar -xvf /tmp/AdGuardHome_linux_armv6.tar.gz &&
cp ./AdGuardHome_linux_armv6/AdGuardHome/AdGuardHome /usr/sbin/adguard && rm -rf /AdGuardHome_linux_armv6 && rm -rf /tmp/AdGuardHome_linux_armv6

# permissions
chown -R alpine:alpine \
	/config \
	/run 

chmod -R g+w \
	/config/{adguard,log}

chmod -R 644 /etc/logrotate.d /config/log
